DWAPlannerROS:
  max_vel_x: 0.7
  min_vel_x: -0.4
  max_vel_theta: 1.0
  min_vel_theta: -0.4
  min_in_place_vel_theta: -0.4
  max_rot_vel: 1.0
  min_rot_vel: -0.4
  acc_lim_x: 1.0
  acc_lim_theta: 0.2          # Reduce to prevent sharp turns
  holonomic_robot: false
  xy_goal_tolerance: 0.2
  yaw_goal_tolerance: 0.1
  latch_xy_goal_tolerance: false

  # Cost function parameters
  path_distance_bias: 32.0    # Increase to follow the path more closely
  goal_distance_bias: 24.0    # Adjust as needed
  occdist_scale: 0.01

  # Oscillation prevention
  oscillation_reset_dist: 0.05
  
  # Other parameters
  forward_point_distance: 0.325
  stop_time_buffer: 0.2
  scaling_speed: 0.25
  max_scaling_factor: 0.2

