obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[x1, y1], [x2, y2], [x3, y3], [x4, y4]]
inflation_radius: 0.55
observation_sources: laser_scan_sensor
laser_scan_sensor: {sensor_frame: laser_frame, data_type: LaserScan, topic: /laser/scan, marking: true, clearing: true}
